### PR TITLE
Add CI.

### PR DESCRIPTION
**Pull request by Zimmi48**
Not tested yet.

### CODE REVIEW

**Comment by Zimmi48** [comment]
CI should have started. It puzzles me that it isn't the case. It may be linked to GitHub's trouble today. Let's see if closing / reopening can trigger the build tomorrow.

**Comment by Zimmi48** [comment]
This CI shows that the branch master is compatible with 8.9 but not with master. Maybe time to create a `v8.9` branch and fix `master` for building with Coq master.

**Comment by herbelin** [comment]
> This CI shows that the branch master is compatible with 8.9 but not with master. Maybe time to create a v8.9 branch and fix master for building with Coq master.

I created a branch v8.9. What is the idea with creating a `master` branch? Is it that each change from a Coq developer which breaks Stalmarck should come with an overlay?

More generally, I missed the information of when the CI shall be activated for stalmarck? Everytime some commit is pushed to the stalmarck repository, everytime a PR is pushed to the stalmarck repository, everytime a PR is pushed to the coq repository?

**Comment by Zimmi48** [comment]
The idea is that CI will be run every day on Travis so if the plugin is broken by a change in Coq, you can know ASAP. However, if you think it is more reasonable to have master track Coq 8.9 and only update the plugin at the time of releases, this is also fine (in this case, I can update the PR to only test for compatibility with `v8.9`). You are the maintainer thus you decide: I'm only providing infrastructure to help.

**Comment by herbelin** [comment]
It would probably be more convenient for me to adapt Stalmarck master in one go rather than at every new incompatibility in Coq master.

Would there be a way to have two lines on the PR page, one showing v8.9 and one showing master, rather than one line, which when clicked, show the two results?

In the meantime, I made master compatible (but probably don't do regularly).

**Comment by Zimmi48** [comment]
>Would there be a way to have two lines on the PR page

You mean without clicking on the "Checks" tab? Unfortunately, that would require a complex setup, for instance using the bot. I could consider doing this at once for all coq-community projects later on.

>In the meantime, I made master compatible

I suppose that this commit is not compatible with Coq 8.9. So, should I adapt my PR on master to only test for compatibility with Coq master, and submit another PR adding CI for v8.9?

>but probably won't do regularly

We could then make `v8.9` the "default" branch (i.e. the branch people will get by default when cloning and to which they will submit PRs by default) so that incoming PRs are tested against a branch that has a green CI. WDYT?

**Comment by herbelin** [comment]
> >  Would there be a way to have two lines on the PR page
> 
> You mean without clicking on the "Checks" tab? Unfortunately, that would require a complex setup, for instance using the bot. I could consider doing this at once for all coq-community projects later on.

OK.

>  > In the meantime, I made master compatible
>
> I suppose that this commit is not compatible with Coq 8.9. 

It is not.

> So, should I adapt my PR on master to only test for compatibility with Coq master, and submit another PR adding CI for v8.9?

As you want.

> We could then make v8.9 the "default" branch (i.e. the branch people will get by default when cloning and to which they will submit PRs by default) so that incoming PRs are tested against a branch that has a green CI. WDYT?

Why not.

**Comment by Zimmi48** [comment]
OK, I'll finish this in a few days.

EDIT: We can also make the CI of master test Coq in "allow failure" mode.

**Comment by Zimmi48** [comment]
Updated: this PR now generates the CI configuration and other files from the templates in https://github.com/coq-community/manifesto.
There are two tests:
- The first one uses the Nix setup and this allows to pin the tested version of Coq to an earlier commit, so that the test passes. When the plugin is updated to compile with a more recent commit, this pinned commit should be updated as well.
- The second one tests the opam package. Because there is no way to test an earlier commit with this setup, it is in "allow failure" mode. One may see the results of both checks by going to the "Checks" tab (see link at the top of the PR thread). It should succeed every time the plugin is updated for compatibility with the latest version of Coq master.

**Comment by Zimmi48** [comment]
@herbelin ping

**Comment by Zimmi48** [comment]
I'm assuming that the comment in #4 on merging myself applied to this PR as well. Note though that this PR pins the version of Coq tested in CI, and thus it should be updated whenever stalmark is updated to compile with more recent versions of Coq...

**Pull request merged**
