### PR TITLE
Travis for 8.9

### PR DESCRIPTION
**Pull request by Zimmi48**
(Add CI and other files generated from templates and `meta.yml`.)
I will also adapt #2 to do the same thing for master.

The second commit is there because of a fix by @vbgl (https://github.com/NixOS/nixpkgs/pull/51325) that has not been merged yet (see also the discussion on the problem that started at . At some point it will be possible to revert this second commit.

### CODE REVIEW

**Comment by vbgl** [comment]
You shouldn’t pin to an ephemeral branch like that. When the PR against `nixpkgs/master` will be merged, I’ll delete the branch and you’ll get a dangling link in the CI script.

Nonetheless, that may not be a big issue in this specific case.

**Comment by Zimmi48** [comment]
Well, if you don't mind, do not delete it right away. @palmskog has already merged a similar fix in aac-tactics branch v8.9

**Comment by Zimmi48** [comment]
@vbgl FTR you can delete this branch. I've removed it from the coq-community branches that were using it.

@herbelin ping (or shall I merge myself)?

**Comment by herbelin** [comment]
> @herbelin ping (or shall I merge myself)?

If you don't mind, I believe that it is indeed as simple if you merge yourself.

**Pull request merged**
