### PR TITLE
Port to mlg, adapt to SProp

### PR DESCRIPTION
**Pull request by palmskog**
This won't pass the Nix-based CI with scripts generated from the templates, since coq-on-cachix is currently stale (does not include SProp changes). @Zimmi48 do you recommend switching back to regular Coq Nix tarballs in CI, or should we do something else?

### CODE REVIEW

**Comment by Zimmi48** [comment]
Ironically, the deploy step updating coq-on-cachix was blocked by Coq's CI failing earlier because of an unmerged SProp overlay. I've manually pushed the update so CI should work again now.

**Comment by Zimmi48** [comment]
@palmskog Should we add you to the maintainer list in stalmarck's `meta.yml`?

**Comment by palmskog** [comment]
@Zimmi48 I can't commit to being a maintainer at this point, however we are using this project actively at the moment for proof engineering research so we want to it to build properly.

**Comment by Zimmi48** [comment]
I see.

**Pull request merged**
